apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
spec:
  selector:
    matchLabels:
      app: auth-service
  replicas: 1
  template:
    metadata:
      labels:
        app: auth-service
    spec:
      containers:
      - name: auth-service
        image: 647223405008.dkr.ecr.me-central-1.amazonaws.com/striderisk-delivery:auth-service_ubuntu_v0-52-0_20042023_dnb_live1
        imagePullPolicy: IfNotPresent
        #volumeMounts:
         # - name: auth-service-logs
          #  mountPath: /var/log/java/auth:/logs
        #livenessProbe:
        #  exec:
        #    command:
        #     - cat
        #     - /auth-service/pom.xml
        #  initialDelaySeconds: 60
        #  periodSeconds: 10
        readinessProbe:
          tcpSocket:
            port: 8888
          initialDelaySeconds: 60
          periodSeconds: 20
          timeoutSeconds: 30
          failureThreshold: 10
          successThreshold: 1
        ports:
        - containerPort: 8888
        envFrom:
          - configMapRef:
              name: java-env-configmap
        resources:
          requests:
            cpu: 500m
            memory: "1000Mi"
          limits:
            cpu: 500m
            memory: "1000Mi"
