apiVersion: v1
kind: Service
metadata:
  name: billing-service
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 8117
    targetPort: 8117
    protocol: TCP
  selector:
    app: billing-service
