apiVersion: v1
kind: Service
metadata:
  name: docparser-gateway-service
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 8070
    targetPort: 8070
    protocol: TCP
  selector:
    app: docparser-gateway-service
