apiVersion: v1
kind: Service
metadata:
  name: gstitr-processor-service
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 8076
    targetPort: 8076
    protocol: TCP
  selector:
    app: gstitr-processor-service
