apiVersion: v1
kind: Service
metadata:
  name: reference-data-service
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 8084
    targetPort: 8084
    protocol: TCP
  selector:
    app: reference-data-service
