apiVersion: v1
kind: Service
metadata:
  name: reporting-service
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 8104
    targetPort: 8104
    protocol: TCP
  selector:
    app: reporting-service
