apiVersion: v1
kind: Service
metadata:
  name: template-management-service
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 8086
    targetPort: 8086
    protocol: TCP
  selector:
    app: template-management-service
