apiVersion: v1
kind: Service
metadata:
  name: xlrt-config-server
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 8101
    targetPort: 8101
    protocol: TCP
  selector:
    app: xlrt-config-server
