version: '3.8'

volumes:
  prometheus_data: {}

services:

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    restart: always
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--web.enable-lifecycle'
    ports:
      - "4003:9090"
    networks:
      - xlrt-cloud-network

  grafana:
    image: grafana/grafana
    container_name: grafana
    restart: always
    ports:
      - "4004:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    networks:
      - xlrt-cloud-network

#  alertmanager:
#    image: prom/alertmanager:v0.12.0
#    ports:
#      - 4005:9093
#    volumes:
#      - ./alertmanager/:/etc/alertmanager/
#    restart: always
#    command:
#      - '-config.file=/etc/alertmanager/config.yml'
#      - '-storage.path=/alertmanager'
networks:
  xlrt-cloud-network:
    external: true