apiVersion: v1
kind: Secret
metadata:
  name: keda-dnb-rabbitmq-python-secret
  namespace: dnb-app
data:
  host: YW1xcHM6Ly9vbmp5b3JzdDpxQy1nVFlPeXVIdFVEYVhMT28xamRaVFg5ZUFBcFA1SkBiZWF2ZXIucm1xLmNsb3VkYW1xcC5jb20vb25qeW9yc3Q=
#echo -n 'amqps://onjyorst:qC-gTYOyuHtUDaXLOo1jdZTX9eAApP5J@beaver.rmq.cloudamqp.com/onjyorst'|base64 -w 0
